name: Build a ZIP and CRX version

on:
  push:
  pull_request:

jobs:
 build:
    runs-on: windows-latest
    steps:   
     - uses: actions/checkout@v2
     - name: Create report file
       run: date +%s > report.txt
       
     - name: Delete old Archive
       run: del "D:\a\Sidebar\Sidebar\Build\Sidebar_latest.zip"
    
     - name: Archive Release
       uses: thedoctor0/zip-release@master
       with:
         type: 'zip'
         filename: 'Sidebar_latest.crx'
         exclusions: '*.git* ./Build/ README.md report.txt'

     - name: Move to "Build" directory
       run: move /y D:\a\Sidebar\Sidebar\Sidebar_latest.zip D:\a\Sidebar\Sidebar\Build\
       shell: cmd

     - name: Build CRX
       run: copy D:\a\Sidebar\Sidebar\Build\Sidebar_latest.zip D:\a\Sidebar\Sidebar\Build\Sidebar_latest.crx
       
     - name: Commit report
       run: |
          git config --global user.name 'Minionguyjpro'
          git config --global user.email 'minionguyjpro@users.noreply.github.com'
          git add -A
          git commit -am "Made new build"
          git push         
