name: CI

on:
  push:
  pull_request:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Create report file
       run: date +%s > report.txt
    
     - name: Archive Release
       uses: thedoctor0/zip-release@master
       with:
         type: 'zip'
         filename: 'Sidebar_latest.zip'
         path: '.'
         directory: './Build/'

     - name: Commit report
       run: |
          git config --global user.name 'Minionguyjpro'
          git config --global user.email 'minionguyjpro@users.noreply.github.com'
          git add -A
          git commit -am "Made new build"
          git push
