name: CI

on:
  push:
  pull_request:

jobs:
 build:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2
     - name: Create report file
       run: date +%s > report.txt

     - name: Compress
       uses: TonyBogdanov/zip@1.0
       with:
           args: zip -qq -r ./Build/Sidebar_latest.zip ./target
     
     - name: Commit report
       run: |
          git config --global user.name 'Minionguyjpro'
          git config --global user.email 'minionguyjpro@users.noreply.github.com'
          git add -A
          git commit -am "Made new build"
          git push
