name: CI

on:
  push:
  pull_request:

jobs:
 report:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2
     - name: Create report file
       run: date +%s > report.txt
       
      - name: Building the installer
        run: Compress-Archive -LiteralPath D:\a\Sidebar\Sidebar\ -DestinationPath D:\a\Sidebar\Sidebar\Build\
        shell: powershell
        
      - name: Commit report
        run: |
           git config --global user.name 'Minionguyjpro'
           git config --global user.email 'minionguyjpro@users.noreply.github.com'
           git add -A
           git commit -am "Made new build"
           git push
